---
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Loading enviroment
## Will change to a enviroment specifically containing only results.
load("C:/Users/Martin/transfer-effect-mistriage/code/globalenv.RData")
```

# Results

We analyseed data from `r sum(data.sets$multi.centre.vs.single.centre$multi.centre$.imp == 0) ` trauma patients. The high and low centre samples contains `r sum(data.sets$high.volume.vs.low.volume$high.volume$.imp==0) ` and `r sum(data.sets$high.volume.vs.low.volume$low.volume$.imp==0)` trauma patients respectively (Table 1). The metropolitan sample and the non-metropolitan sample contains `r sum(data.sets$metropolitan.vs.non.metropolitan$metropolitan$.imp==0) ` and `r sum(data.sets$metropolitan.vs.non.metropolitan$non.metropolitan$.imp==0) ` respectively (Table 2). The multi centre sample constitutes the total number of trauma patients. We identified only one valid single centre. which contains `r  sum(data.sets$multi.centre.vs.single.centre$single.centre.11001$.imp==0) ` trauma patients (Table 3). The data presented in each table is multiple imputed. The number of imputations used is `r number.of.imputations  `, which is equal to the maximum percentage of missing data found across the data sets.

All samples were similar regarding age, GCS, SBP and RR. The percentage of missing data in the high and low volume sampes were `r NA.info.sample$high.volume.vs.low.volume$high.volume$percent.NA`% and `r NA.info.sample$high.volume.vs.low.volume$low.volume$percent.NA`%. ...
